/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Geral
 */
public class AdminInfo extends javax.swing.JFrame {

    /**
     * Creates new form kkk
     */
    public AdminInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tttCpf10 = new javax.swing.JLabel();
        tttCpf11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        telaCadastraUsuario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jcMaquina = new javax.swing.JComboBox();
        tttDisponivel = new javax.swing.JLabel();
        tttCpf13 = new javax.swing.JLabel();
        tttCpf14 = new javax.swing.JLabel();
        tttIdTecido = new javax.swing.JLabel();
        tttId = new javax.swing.JLabel();
        tttVendido = new javax.swing.JLabel();
        tttCpf16 = new javax.swing.JLabel();
        tttCpf19 = new javax.swing.JLabel();
        jcTecido = new javax.swing.JComboBox();
        tttCpf20 = new javax.swing.JLabel();
        tttCpf21 = new javax.swing.JLabel();
        tttCpf22 = new javax.swing.JLabel();
        tttIDfornecedor = new javax.swing.JLabel();
        tttManutencao = new javax.swing.JLabel();
        tttDescricao = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnAtualizarMaquina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel5.setBackground(new java.awt.Color(237, 223, 196));
        jlabel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jlabel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 659, -1, -1));
        jlabel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 463, -1, -1));
        jlabel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 283, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jlabel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, -1, 144));
        jlabel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 295, 185, -1));

        tttCpf10.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        tttCpf10.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf10.setText("Maquina");
        jlabel5.add(tttCpf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 315, -1));

        tttCpf11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf11.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf11.setText("ID fornecedor:");
        jlabel5.add(tttCpf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, -1));

        jPanel5.setBackground(new java.awt.Color(54, 31, 37));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(237, 223, 196));
        jLabel29.setText("Cadastrar novo usuario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(45, 45, 45))
        );

        jlabel5.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 130));

        telaCadastraUsuario.setText("Voltar");
        jlabel5.add(telaCadastraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, -1, -1));

        jPanel6.setBackground(new java.awt.Color(54, 31, 37));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(237, 223, 196));

        jPanel7.setBackground(new java.awt.Color(54, 31, 37));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(237, 223, 196));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel31)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel30)
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jlabel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 20, 550));

        jPanel8.setBackground(new java.awt.Color(54, 31, 37));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(237, 223, 196));

        jPanel9.setBackground(new java.awt.Color(54, 31, 37));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(237, 223, 196));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel33)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel32)
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jlabel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 30, 540));

        jPanel10.setBackground(new java.awt.Color(54, 31, 37));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(237, 223, 196));

        jPanel11.setBackground(new java.awt.Color(54, 31, 37));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(237, 223, 196));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel35)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel34)
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jlabel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 20, 550));

        jPanel13.setBackground(new java.awt.Color(54, 31, 37));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jlabel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 40));

        jcMaquina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione a Maquina>" }));
        jlabel5.add(jcMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 240, 30));

        tttDisponivel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttDisponivel.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttDisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 280, 20));

        tttCpf13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf13.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf13.setText("Descrição:");
        jlabel5.add(tttCpf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, -1));

        tttCpf14.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf14.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf14.setText("Manutenção:");
        jlabel5.add(tttCpf14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 110, -1));

        tttIdTecido.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttIdTecido.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttIdTecido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 220, 30));

        tttId.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttId.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttId, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 220, 20));

        tttVendido.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttVendido.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 280, 20));

        tttCpf16.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf16.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf16.setText("ID:");
        jlabel5.add(tttCpf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 30, -1));

        tttCpf19.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        tttCpf19.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf19.setText("Tecidos");
        jlabel5.add(tttCpf19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 315, -1));

        jcTecido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o Tecido>" }));
        jlabel5.add(jcTecido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 240, 30));

        tttCpf20.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf20.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf20.setText("ID:");
        jlabel5.add(tttCpf20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 30, -1));

        tttCpf21.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf21.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf21.setText("Disponivel:");
        jlabel5.add(tttCpf21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, -1));

        tttCpf22.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf22.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf22.setText("Vendido:");
        jlabel5.add(tttCpf22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, -1));

        tttIDfornecedor.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttIDfornecedor.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttIDfornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 270, 20));

        tttManutencao.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttManutencao.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 220, 20));

        tttDescricao.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttDescricao.setForeground(new java.awt.Color(54, 31, 37));
        jlabel5.add(tttDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 220, 20));

        btnAtualizar.setText("Atualizar");
        jlabel5.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        btnAtualizarMaquina.setText("Atualizar");
        btnAtualizarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarMaquinaActionPerformed(evt);
            }
        });
        jlabel5.add(btnAtualizarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarMaquinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtualizar;
    public javax.swing.JButton btnAtualizarMaquina;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JComboBox jcMaquina;
    public javax.swing.JComboBox jcTecido;
    private javax.swing.JPanel jlabel5;
    public javax.swing.JButton telaCadastraUsuario;
    private javax.swing.JLabel tttCpf10;
    public javax.swing.JLabel tttCpf11;
    public javax.swing.JLabel tttCpf13;
    public javax.swing.JLabel tttCpf14;
    public javax.swing.JLabel tttCpf16;
    public javax.swing.JLabel tttCpf19;
    public javax.swing.JLabel tttCpf20;
    public javax.swing.JLabel tttCpf21;
    public javax.swing.JLabel tttCpf22;
    public javax.swing.JLabel tttDescricao;
    public javax.swing.JLabel tttDisponivel;
    public javax.swing.JLabel tttIDfornecedor;
    public javax.swing.JLabel tttId;
    public javax.swing.JLabel tttIdTecido;
    public javax.swing.JLabel tttManutencao;
    public javax.swing.JLabel tttVendido;
    // End of variables declaration//GEN-END:variables
}
