/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Geral
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        tttCpf9 = new javax.swing.JLabel();
        tttCpf10 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        tttCpf11 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        passSenha = new javax.swing.JPasswordField();
        passConfirma = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        cxAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel5.setBackground(new java.awt.Color(237, 223, 196));
        jlabel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jlabel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 659, -1, -1));
        jlabel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 463, -1, -1));
        jlabel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 283, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jlabel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, 144));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 31, 37));
        jLabel26.setText("Nome Completo");
        jlabel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 315, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jlabel5.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 193, 25));
        jlabel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 295, 185, -1));

        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });
        jlabel5.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 193, 25));

        tttCpf9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf9.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf9.setText("Horario de Trabalho");
        jlabel5.add(tttCpf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 315, -1));

        tttCpf10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf10.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf10.setText("CPF");
        jlabel5.add(tttCpf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 315, -1));

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jlabel5.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 193, 25));

        tttCpf11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tttCpf11.setForeground(new java.awt.Color(54, 31, 37));
        tttCpf11.setText("Salario");
        jlabel5.add(tttCpf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 315, -1));

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        jlabel5.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 193, 25));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 31, 37));
        jLabel5.setText("Usuario");
        jlabel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 315, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(54, 31, 37));
        jLabel12.setText("Senha");
        jlabel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 315, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 31, 37));
        jLabel19.setText("Confirme a Senha");
        jlabel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 315, -1));

        jPanel5.setBackground(new java.awt.Color(54, 31, 37));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(237, 223, 196));
        jLabel29.setText("Cadastrar novo usuario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel29)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jlabel5.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 130));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jlabel5.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 193, 25));
        jlabel5.add(passSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 200, 30));
        jlabel5.add(passConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 200, 30));

        btnCadastrar.setText("Cadastrar");
        jlabel5.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 100, 30));

        cxAdmin.setBackground(new java.awt.Color(237, 223, 196));
        cxAdmin.setText("O usuario será um administrador");
        cxAdmin.setActionCommand("O usuario será um administrador");
        jlabel5.add(cxAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCadastrar;
    public javax.swing.JCheckBox cxAdmin;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jlabel5;
    public javax.swing.JPasswordField passConfirma;
    public javax.swing.JPasswordField passSenha;
    public javax.swing.JLabel tttCpf10;
    public javax.swing.JLabel tttCpf11;
    public javax.swing.JLabel tttCpf9;
    public javax.swing.JTextField txtCpf;
    public javax.swing.JTextField txtHorario;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtSalario;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
